//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_Experimental_Director_DirectorPlayerWrap
{
	public static void Register(LuaState L)
	{
	}
}

